version: 2

models:

    - name: sales
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            tests : 
            - not_null 

          - name: products_id
            tests : 
            - not_null 
          

          - name: qty
            tests : 
            - not_null 

          - name: turnover
            tests : 
            - not_null 

          - name: purchase_cost
            tests : 
            - not_null 

          - name: margin
            tests : 
            - not_null 